function Footer() {
    return (
        <footer class="bg-neutral-200 text-center dark:bg-neutral-950 pb-5">
            <div class="p-4 text-center text-neutral-200 cursor-pointer">
                © 2024 Copyright: Urban Cafe || By AI
            </div>
            <h1 className="font-bold text-white mb-5">
                Made with React and Tailwind CSS
            </h1>
            <div className="text-neutral-200">
                <h1 className="font-bold">Credit:</h1>

                <p>Menu Images generated by Microsoft Bing AI</p>
                <p>
                    Jonathan Sanchez, Mike Kenneally, Nathan Dumlao for Coffee
                    Image in "Unsplashed"
                </p>
                <p>Another Coffee Image found in "The Economic Times"</p>
            </div>
        </footer>
    );
}

export default Footer;
